Repository wedding-planner-app/wedding-planner, pull requests merged in 2020-08, with the labels that each got.

#93 Added new wireframes
  README.md
  readme/imgs/wireframe-guestlist.png
  readme/imgs/wireframe-media.png
Labels: documentation, frontend, mvp

#96 User Authentication
  client/package.json
  client/src/App.js
  client/src/auth0-provider-with-history.js
  client/src/components/Button/index.js
  client/src/components/Loading/index.js
  client/src/components/LoginLink/index.js
  client/src/components/LogoutLink/index.js
  client/src/components/NavigationBar/index.js
  client/src/components/PrivateRoute/index.js
  client/src/components/SignupLink/index.js
  client/src/index.js
  client/src/pages/Events/index.js
  client/src/pages/Profile/index.js
  client/src/pages/Profile/style.css
Labels: authentication, backend, frontend, mvp

#104 Nav Bar
  client/src/components/LoginLink/index.js
  client/src/components/LogoutLink/index.js
  client/src/components/NavigationBar/index.js
  client/src/components/NavigationBar/style.css
  client/src/components/ProfileLink/index.js
  client/src/components/SignupLink/index.js
  client/src/pages/Guests/style.css
  client/src/pages/Media/style.css
  client/src/pages/Profile/index.js
Labels: frontend

#105 Integrated Auth0 with APIs and Controller Wedding Develop
  client/src/auth0-provider-with-history.js
  client/src/components/NavigationBar/style.css
  client/src/components/WeddingCard/index.js
  client/src/components/WeddingCard/style.css
  client/src/pages/Events/index.js
  client/src/pages/Login/index.js
  client/src/pages/Login/style.css
  client/src/pages/Login/user.png
  client/src/pages/Logout/index.js
  client/src/pages/NewReservation/index.js
  client/src/pages/SignUp/index.js
  client/src/pages/SignUp/style.css
  client/src/pages/SignUp/user.png
  controllers/api/guests.js
  controllers/api/index.js
  controllers/api/user.js
  controllers/api/wedding.js
  controllers/index.js
  models/user.js
  models/wedding.js
  package.json
  server.js
Labels: api, backend, db, frontend, mvp

#112 Create new wedding event
  client/src/pages/NewReservation/index.js
  client/src/pages/NewReservation/style.css
Labels: backend, frontend, mvp

#115 Delete event
  client/src/App.js
  client/src/components/WeddingCard/index.js
  client/src/pages/Events/index.js
  client/src/pages/NewReservation/index.js
Labels: api, backend, frontend, mvp

#116 Secure Venue, Venue, Guest API
  controllers/api/guests.js
  controllers/api/media.js
  controllers/api/venue.js
Labels: api, backend, db, mvp

#120 Updates venue component to use hooks
  client/src/components/VenuesPageComponent/index.js
  controllers/api/index.js
  controllers/api/venue-images.js
  controllers/api/venue.js
Labels: api, backend, bug, db, debug, frontend

#123 Updated readme with architecture diagram and mvp
  README.md
  readme/imgs/architecture-diagram.png
Labels: documentation

#126 Create and list guests
  client/src/components/SearchTable/index.js
  client/src/pages/Events/index.js
  client/src/pages/Guests/index.js
  client/src/pages/Guests/style.css
  controllers/api/guests.js
Labels: mvp

#127 Guest delete and edit
  client/src/components/WeddingCard/index.js
  client/src/components/WeddingCard/style.css
  client/src/pages/Guests/index.js
  client/src/pages/NewReservation/index.js
Labels: mvp

#128 Assign Venue to Weddings
  client/src/components/VenueCard/index.js
  client/src/components/VenuesPageComponent/index.js
  client/src/pages/Home/index.js
  client/src/pages/Venue/index.js
  config/config.json
  controllers/api/index.js
  controllers/api/venue.js
Labels: api, backend, db, heroku, mvp

#133 Update ER diagram
  README.md
  readme/imgs/schema.png
Labels: documentation

#139 Api documentation potsman
  README.md
  client/src/components/Button/style.css
  client/src/components/Carousel/index.js
  client/src/components/FirstName/index.js
  client/src/components/FirstName/style.css
  client/src/components/LastName/index.js
  client/src/components/LastName/style.css
  client/src/components/NavigationBar/style.css
  client/src/components/Password/index.js
  client/src/components/Password/style.css
  client/src/components/VenuesPageComponent/index.js
  client/src/pages/Events/index.js
  client/src/pages/Guests/index.js
  client/src/pages/Media/index.js
  client/src/pages/NewReservation/index.js
  client/src/pages/NewReservation/style.css
  client/src/pages/Profile/index.js
  client/src/pages/Venue/index.js
  config/config.json
  readme/imgs/p.png
  readme/imgs/postman.png
Labels: bug, documentation

#142 Readme Update
  README.md
  readme/imgs/MVCfolderPattern.png
  readme/imgs/packageJsonClient.png
  readme/imgs/packageJsonRoot.png
  readme/imgs/wireframe-guestlist.png
  readme/imgs/wireframe-signup.png
Labels: documentation

#144 Fix readme typos
  README.md
Labels: documentation

#145 Issue 108 invitation controller
  client/src/pages/Guests/index.js
  config/config.json
  controllers/api/guests.js
  controllers/api/invitation.js
Labels: backend, frontend, mvp

#147 UI Validations
  README.md
  client/public/favicon.ico
  client/src/components/Button/index.js
  client/src/components/Button/style.css
  client/src/components/InfoCard/style.css
  client/src/components/VenuesPageComponent/index.js
  client/src/pages/Events/index.js
  client/src/pages/Guests/index.js
  client/src/pages/Guests/style.css
  client/src/pages/NewReservation/index.js
  client/src/pages/NewReservation/style.css
  config/config.json
Labels: backend, frontend, validations

#149 141 ui
  client/src/components/VenuesPageComponent/index.js
  client/src/pages/Events/index.js
Labels: frontend

#151 Readme last update
  README.md
  client/package.json
  readme/imgs/packageJsonClient.png
  readme/imgs/packageJsonRoot.png
Labels: documentation
