Repository wedding-planner-app/wedding-planner, pull requests merged in 2020-07, with the labels that each got.

#2 Proposal readme
  README.md
  assets/imgs/readme/logo.png
  assets/imgs/readme/wireframe1.png
Labels: documentation, proposal

#3 Updated proposal readme
  README.md
  assets/imgs/readme/uml.png
Labels: documentation, proposal

#4 Updated readme
  README.md
  assets/imgs/readme/schema.png
  assets/imgs/readme/wb1.png
  assets/imgs/readme/wb2.png
Labels: documentation

#6 5 update wireframes
  README.md
  assets/imgs/readme/wireframe1-homepage.png
  assets/imgs/readme/wireframe1.png
  assets/imgs/readme/wireframe2-login.png
Labels: documentation

#9 Project setup
  .eslintrc.json
  .gitignore
  .prettierrc
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/components/Form/index.js
  client/src/components/Form/style.css
  client/src/index.js
  config/config.json
  controllers/api/index.js
  controllers/api/user.js
  controllers/index.js
  models/index.js
  models/user.js
  package.json
  server.js
Labels: mvp

#12 7 remaining wireframes
  README.md
  assets/imgs/readme/wireframe-guestlist.png
  assets/imgs/readme/wireframe-homepage.png
  assets/imgs/readme/wireframe-invitations.png
  assets/imgs/readme/wireframe-login.png
  assets/imgs/readme/wireframe-reservation.png
  assets/imgs/readme/wireframe-signup.png
  assets/imgs/readme/wireframe-venues.png
  assets/imgs/readme/wireframe1-homepage.png
  assets/imgs/readme/wireframe2-login.png
Labels: documentation

#14 Structure update
  README.md
  client/public/index.html
  client/src/App.js
  client/src/App.test.js
  client/src/components/Component.js
  client/src/components/Form/index.js
  client/src/components/Form/style.css
  client/src/components/style.css
  client/src/index.js
  config/config.json
  readme/imgs/logo.png
  readme/imgs/schema.png
  readme/imgs/uml.png
  readme/imgs/wb1.png
  readme/imgs/wb2.png
  readme/imgs/wireframe-guestlist.png
  readme/imgs/wireframe-homepage.png
  readme/imgs/wireframe-invitations.png
  readme/imgs/wireframe-login.png
  readme/imgs/wireframe-reservation.png
  readme/imgs/wireframe-signup.png
  readme/imgs/wireframe-venues.png
  scripts/schema.sql
  scripts/seedDB.js
Labels: mvp

#18 Navbar component
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Component.js
  client/src/components/NavigationBar/index.js
  client/src/components/NavigationBar/logo.png
  client/src/components/NavigationBar/style.css
  client/src/components/style.css
  client/src/pages/Events/index.js
  client/src/pages/Login/index.js
  client/src/pages/Logout/index.js
  client/src/pages/Profile/index.js
  client/src/pages/SignUp/index.js
  package.json
  readme/imgs/logo.png
Labels: frontend, mvp

#20 Adding a profile wireframe
  README.md
  readme/imgs/wireframe-newReservation.png
  readme/imgs/wireframe-profile.png
Labels: documentation

#21 Added footer component
  client/src/App.js
  client/src/components/Footer/favicon.ico
  client/src/components/Footer/index.js
  client/src/components/Footer/style.css
Labels: mvp

#22 Homepage carousel and message components
  README.md
  client/package.json
  client/src/App.js
  client/src/components/Carousel/imgs/bride.jpg
  client/src/components/Carousel/imgs/heart.jpg
  client/src/components/Carousel/imgs/venues.jpg
  client/src/components/Carousel/imgs/weddings.jpg
  client/src/components/Carousel/index.js
  client/src/components/Carousel/style.css
  client/src/components/Footer/favicon.ico
  client/src/components/Footer/index.js
  client/src/components/Footer/style.css
  client/src/components/Message/index.js
  client/src/components/Message/style.css
  client/src/components/NavigationBar/index.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.css
Labels: frontend, mvp

#24 Cards component
  client/src/App.js
  client/src/components/Carousel/imgs/bride-modified.jpg
  client/src/components/Carousel/imgs/heart-modified.jpg
  client/src/components/Carousel/imgs/venues.jpg
  client/src/components/Carousel/imgs/weddings-modified.jpg
  client/src/components/Carousel/index.js
  client/src/components/Footer/style.css
  client/src/components/InfoCard/index.js
  client/src/components/InfoCard/style.css
  client/src/components/Message/index.js
  client/src/components/Message/style.css
  client/src/pages/Home/imgs/guests-modified.png
  client/src/pages/Home/imgs/guests.png
  client/src/pages/Home/imgs/invitations.png
  client/src/pages/Home/imgs/media.png
  client/src/pages/Home/imgs/venues.jpg
  client/src/pages/Home/index.js
Labels: frontend, mvp

#28 Login In Components
  client/src/App.test.js
  client/src/components/Button/index.js
  client/src/components/Button/style.css
  client/src/components/Email/index.js
  client/src/components/Email/style.css
  client/src/components/Password/index.js
  client/src/components/Password/style.css
  client/src/pages/Login/index.js
  client/src/pages/Login/style.css
  client/src/pages/Login/user.png
Labels: frontend, mvp

#30 Redo of profile wireframe
  README.md
  readme/imgs/wireframe-existingReservations.png
  readme/imgs/wireframe-profile.png
Labels: documentation

#31 Event page
  client/src/components/WeddingCard/index.js
  client/src/components/WeddingCard/style.css
  client/src/pages/Events/index.js
  client/src/pages/Events/logo.png
  client/src/pages/Events/style.css
Labels: frontend, mvp

#35 Signup page UI components
  client/src/components/Button/index.js
  client/src/components/Email/index.js
  client/src/components/NavigationBar/index.js
  client/src/pages/Home/imgs/guest.png
  client/src/pages/Home/imgs/guests.png
  client/src/pages/Home/imgs/media.jpeg
  client/src/pages/Home/imgs/media.png
  client/src/pages/Home/index.js
  client/src/pages/Login/index.js
  client/src/pages/SignUp/index.js
  client/src/pages/SignUp/style.css
  client/src/pages/SignUp/user.png
Labels: frontend, mvp

#37 Hosted App Link
  README.md
  client/src/components/InfoCard/style.css
  config/config.json
  package.json
Labels: heroku, mvp

#44 Created basic venue model
  models/venue.js
  package.json
Labels: backend, mvp

#45 Wedding model
  client/src/components/InfoCard/index.js
  client/src/components/InfoCard/style.css
  client/src/components/NavigationBar/index.js
  client/src/components/NavigationBar/style.css
  client/src/components/WeddingCard/index.js
  client/src/pages/Events/index.js
  client/src/pages/Home/index.js
  client/src/pages/SignUp/index.js
  client/src/pages/SignUp/style.css
  models/wedding.js
Labels: backend, frontend, mvp

#48 User model
  client/src/components/RSVPInfoCard/index.js
  client/src/pages/Invitation-RSVP/index.js
  models/user.js
  models/wedding.js
Labels: backend, mvp

#52 Media model
  models/media.js
  models/user.js
  models/wedding.js
Labels: backend, mvp

#54 51 update venue model
  models/venue.js
Labels: backend, mvp

#57 Invitation model
  models/invitation.js
  models/venue.js
Labels: backend, mvp

#59 Added quest object
  .vscode/settings.json
  config/config.json
  models/guest.js
  models/invitation.js
  models/media.js
  models/wedding.js
Labels: backend, mvp

#60 Issue 43 develop guests pagew/components
  client/package.json
  client/src/App.js
  client/src/components/SearchTable/index.js
  client/src/pages/Guests/index.js
  client/src/pages/Guests/style.css
Labels: frontend, mvp

#65 Added create Btn to Events Page
  client/src/pages/Events/index.js
  client/src/pages/Events/style.css
Labels: frontend, mvp

#70 Fixed Wedding Associations (FK) and added Basic structure API route for Weeding
  config/config.json
  controllers/api/index.js
  controllers/api/wedding.js
  controllers/index.js
  models/media.js
  models/wedding.js
Labels: api, backend, bug, db, debug

#73 Wedding API CRUD
  controllers/api/index.js
  controllers/api/wedding.js
Labels: api, backend, db, mvp

#74 User API CRUD
  controllers/api/user.js
  controllers/api/wedding.js
Labels: api, backend, db, mvp

#76 62 fix responsiveness
  client/src/components/Email/index.js
  client/src/components/FirstName/index.js
  client/src/components/FirstName/style.css
  client/src/components/InputText/style.css
  client/src/components/LastName/index.js
  client/src/components/Password/index.js
  client/src/pages/Login/index.js
  client/src/pages/Login/style.css
  client/src/pages/NewReservation/index.js
  client/src/pages/NewReservation/style.css
  client/src/pages/Profile/index.js
  client/src/pages/Profile/style.css
  client/src/pages/SignUp/index.js
  client/src/pages/Venue/index.js
  client/src/pages/Venue/style.css
Labels: bug, frontend, mvp

#79 User Action Login
  client/package.json
  client/src/components/Button/index.js
  client/src/components/Email/index.js
  client/src/components/Password/index.js
  client/src/pages/Login/index.js
  controllers/api/user.js
Labels: api, backend, db, mvp

#81 Developed Invitation API
  .vscode/settings.json
  config/config.json
  controllers/api/index.js
  controllers/api/invitation.js
  models/wedding.js
Labels: api, backend, mvp

#83 Added media API
  .vscode/settings.json
  controllers/api/index.js
  controllers/api/media.js
Labels: api, backend, mvp

#86 Venue API CRUD
  controllers/api/index.js
  controllers/api/venue.js
Labels: api, backend, db, frontend

#92 Issue 66 guest api db queries
  config/config.json
  controllers/api/guests.js
  controllers/api/index.js
Labels: api, backend, db, mvp
